First attempt to reload core during post schema.
stevector/search_api_pantheon pull request #189
Opened 2024-11-08 21:07 UTC by kporras07

2024-11-08 21:07 UTC, kporras07 commented on src/Services/Endpoint.php
> +    return vsprintf(
this function should be reimplemented

2024-11-08 21:08 UTC, kporras07 commented on src/Services/SchemaPoster.php
> +    $this->logger->info('After server reload?');
extra debugging logging we should remove

2024-11-12 18:09 UTC, stovak requested changes, later dismissed
I think you need two things... 1. Change the way it gets the reload URL to the environment variable. 2. do a command to do the reload from drush.

2024-11-12 18:09 UTC, stovak commented on src/Services/Endpoint.php
> +    return vsprintf(
Kevin is correct. You'll need to get the reload URL from the env var.

2024-11-12 18:09 UTC, stovak commented on src/Services/SchemaPoster.php
> +    $this->logger->info('After server reload?');
I would leave ALL of the debugging in until you have a release ready. Also I could do a drush command to call the reload as well.

2024-11-12 18:12 UTC, stovak commented
Also having a drush command will help you debug the process once we get to testing. Once you know the drush command works and you can trigger it at will, you can know that as long as the UI is triggering that function, all is working as it should.

2024-11-12 18:14 UTC, kporras07 commented
I'm unsure whether reloading as a standalone command is needed/makes sense. AFAIK the goal is to make reload happen automatically on schema post

2024-11-12 22:03 UTC, pwtyler commented on tests/Unit/EndpointServiceTest.php
> +    );
```suggestion
```

2024-11-13 00:07 UTC, pwtyler commented on src/Commands/Reload.php
> +  }
This currently doesn't display anything, not sure the idomatic way to write a drush command so this is bare bones.

2024-11-13 00:17 UTC, pwtyler commented on .gitignore
> +.envrc
```suggestion
.envrc

```

2024-11-13 02:22 UTC, pwtyler approved these changes, later dismissed
Been a number of hands on this. +1 to cut a release and get a fix out with the caveat that unit tests are failing (and were failing before this PR) and units are not running in CI.

2024-11-13 05:50 UTC, pwtyler commented
I've backed out the changes to PantheonSolrConnector (a6b1488 and its subsequent fixes), as we encountered an exception thrown from the dash running reload core at `/admin/config/search/search-api/server/pantheon_blog_solr8/solr-admin/reload-core`.

```
Message	RuntimeException: Unable to instantiate Schema Poster. in Drupal\search_api_pantheon\Plugin\SolrConnector\PantheonSolrConnector->reloadCore() (line 409 of /code/web/modules/contrib/search_api_pantheon/src/Plugin/SolrConnector/PantheonSolrConnector.php).
```

`drush search-api-pantheon:postSchema` and `/admin/config/search/search-api/server/pantheon_solr8/pantheon-admin/schema` seem fine though. still adovcating Reload Core may be best as follow-on work unless there's an important gap I'm missing here.

2024-11-13 05:50 UTC, pwtyler submitted a review, later dismissed

2024-11-13 14:33 UTC, namespacebrian approved these changes, later dismissed

2024-11-14 06:22 UTC, pwtyler commented
Replacing this with #192. `git diff c4383b0 65a5c94` shows no difference. That PR will be our workspace for future iteration on the currently broken "reload core".

2024-11-14 06:22 UTC, closed without merging